### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs-website#107]
Moved from https://github.com/tensorflow/tfjs/issues/42.

@tambry:
Unlike [the Tensorflow website](https://www.tensorflow.org) itself, [the website for Tensorflow.js](https://js.tensorflow.org) is inaccessible over IPv6.

**Comment by tafsiri** [comment]
I don't think this is supported by our underlying host so we probably wont be able to fix it ourselves. If it prevents someone from accessing the site we could probably escalate that.
