### ISSUE TITLE
Problem with deeplearnjs.org certificates

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs-website#151]
Chrome warn me "Your connection is not private"

![image](https://user-images.githubusercontent.com/547150/40068063-b2d55e4c-5835-11e8-9e9a-15aadf3024ff.png)

See original issue at https://github.com/tensorflow/tfjs/issues/297

**Comment by tafsiri** [comment]
Thanks for reporting. This has effectively been resolved as we've sunset deeplearnjs.org in favor of js.tensorflow.org.
