### ISSUE TITLE
[Doc generator] Change symbol references in documentation to require "tf." prefix.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs-website#53]
Sometimes we refer to `ones` as one of the string arguments, sometimes it refers to the function `tf.ones`. To disambiguate, we should force you to use `tf.` when referring to symbols on `tf.`.

I don't want to do this before the launch because it will require a major change to the deeplearn.js docs which we can't do in public yet.

**Comment by tafsiri** [comment]
This issue was moved to tensorflow/tfjs#361
